var trees = [
  {
    "Number": 1,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003864",
    "lng": "W-87.657552",
    "dbh": 26.7,
    "height": "40'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "2 trunks"
  },
  {
    "Number": 2,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003827",
    "lng": "W-87.657528",
    "dbh": 10.3,
    "height": "28'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 3,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003860",
    "lng": "W-87.657382",
    "dbh": 14.9,
    "height": "28'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 1,
    "Notes": "2 trunks-diverge at base"
  },
  {
    "Number": 4,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003835",
    "lng": "W-87.657391",
    "dbh": 10.3,
    "height": "25'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 5,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003872",
    "lng": "W-87.657366",
    "dbh": 9.6,
    "height": "25'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 6,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003859",
    "lng": "W-87.657319",
    "dbh": 12.1,
    "height": "25'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 7,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003813",
    "lng": "W-87.657297",
    "dbh": 10.1,
    "height": "25'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 8,
    "Species": "Box Elder (Acer negundo)",
    "lat": "N42.003824",
    "lng": "W-87.657657",
    "dbh": 6.75,
    "height": "10'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "Volunteer along fence"
  },
  {
    "Number": 9,
    "Species": "Box Elder (Acer negundo)",
    "lat": "N42.00385",
    "lng": "W-87.657636",
    "dbh": 1.2,
    "height": "was 9' (1.5')",
    "Crown Condition": 1,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "Volunteer along fence (Revised condition March 2018-have been hacked off)"
  },
  {
    "Number": 10,
    "Species": "Ailanthus altissima",
    "lat": "N42.003883",
    "lng": "W-87.657644",
    "dbh": ".47",
    "height": "was 8' (1.5')",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 3,
    "Notes": "Volunteer along fence (Revised condition March 2018-March 2018-have been hacked off)"
  },
  {
    "Number": 11,
    "Species": "White Mulberry (Morus alba)",
    "lat": "N42.003896",
    "lng": "W-87.657641",
    "dbh": ".5",
    "height": "was 11' (1.5')",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "Volunteer along fence (Revised condition March 2018-March 2018-have been hacked off). Many shoots from stump"
  },
  {
    "Number": 12,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.003977",
    "lng": "W-87.657629",
    "dbh": 12.5,
    "height": "28'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "Leaf spot"
  },
  {
    "Number": 13,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.003987",
    "lng": "W-87.657630",
    "dbh": 2.6,
    "height": "17'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 14,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.004044",
    "lng": "W-87.657641",
    "dbh": 10.5,
    "height": "32'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "Leaf spot"
  },
  {
    "Number": 15,
    "Species": "Ailanthus altissima",
    "lat": "N42.004110",
    "lng": "W-87.657667",
    "dbh": 18.4,
    "height": "45'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 16,
    "Species": "Ailanthus altissima",
    "lat": "N42.004140",
    "lng": "W-87.657677",
    "dbh": 16.8,
    "height": "45'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 17,
    "Species": "Ailanthus altissima",
    "lat": "N42.004178",
    "lng": "W-87.657695",
    "dbh": 18.9,
    "height": "44'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 18,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.005041",
    "lng": "W-87.657577",
    "dbh": 3.2,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "Growing in sand next to light pole; 2-trunked; epicormic sprouts; some bare spots on bark. Likely a volunteer"
  },
  {
    "Number": 19,
    "Species": "Eastern Cottonwood (Populus deltoides)",
    "lat": "N42.005245",
    "lng": "W-87.657828",
    "dbh": 16.9,
    "height": "30'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Growing in sand; 2-trunked"
  },
  {
    "Number": 20,
    "Species": "Eastern Cottonwood (Populus deltoides)",
    "lat": "N42.005309",
    "lng": "W-87.657779",
    "dbh": 29.6,
    "height": "45'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "Growing in sand; 2-trunked; enclosed bark"
  },
  {
    "Number": 21,
    "Species": "Ailanthus Altissima",
    "lat": "N42.005347",
    "lng": "W-87.657843",
    "dbh": 17.2,
    "height": "38'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "Vertical cracks in bark; metal hook getting enclosed by tree"
  },
  {
    "Number": 22,
    "Species": "Ailanthus Altissima",
    "lat": "N42.005417",
    "lng": "W-87.657840",
    "dbh": 16.5,
    "height": "39'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "metal hook getting enclosed by tree"
  },
  {
    "Number": 23,
    "Species": "Box Elder (Acer negundo)",
    "lat": "N42.005418",
    "lng": "W-87.657840",
    "dbh": 15.9,
    "height": "32'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "leaning trunk; many sprouts at base of tree"
  },
  {
    "Number": 24,
    "Species": "White Ash (Fraxinus pennsylvanica)",
    "lat": "N42.005445",
    "lng": "W-87.657805",
    "dbh": 6.7,
    "height": "35'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "some dead branches"
  },
  {
    "Number": 25,
    "Species": "Siberian Elm (Ulmus pumila)",
    "lat": "N42.005422",
    "lng": "W-87.657872",
    "dbh": 20.2,
    "height": "32'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "growing near concrete; enclosed bark"
  },
  {
    "Number": 26,
    "Species": "Ailanthus altissima",
    "lat": "N42.005475",
    "lng": "W-87.657892",
    "dbh": 20,
    "height": "31'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "growing near concrete; broken branches"
  },
  {
    "Number": 27,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.005792 (+/-16 ft)",
    "lng": "W-87.658408",
    "dbh": 24.2,
    "height": "60'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "girdling roots"
  },
  {
    "Number": 28,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.005917",
    "lng": "W-87.658252",
    "dbh": 24.2,
    "height": "50'",
    "Crown Condition": 3,
    "Trunk Condition": 1,
    "Root Condition": 1,
    "Notes": "girdling roots; large trunk gash from limb loss"
  },
  {
    "Number": 29,
    "Species": "Little-leaf Linden (Tilia cordata)",
    "lat": "N42.005811",
    "lng": "W-87.658255",
    "dbh": 23.2,
    "height": "65'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 1,
    "Notes": "girdling roots"
  },
  {
    "Number": 30,
    "Species": "Silver Maple (Acer saccharinum)",
    "lat": "N42.006169",
    "lng": "W-87.658378",
    "dbh": 28.3,
    "height": "60'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "girdling roots; old trunk injury"
  },
  {
    "Number": 31,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.005947",
    "lng": "W-87.658317",
    "dbh": 20.7,
    "height": "55'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "root damage from mower"
  },
  {
    "Number": 32,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006161",
    "lng": "W-87.658203",
    "dbh": 16.8,
    "height": "55'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "root damage from mower"
  },
  {
    "Number": 33,
    "Species": "Silver Maple (Acer saccharinum)",
    "lat": "N42.006211",
    "lng": "W-87.658395",
    "dbh": 34.6,
    "height": "55'",
    "Crown Condition": 3,
    "Trunk Condition": 1,
    "Root Condition": 3,
    "Notes": "base of trunk looks hollow"
  },
  {
    "Number": 34,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006260",
    "lng": "W-87.658290",
    "dbh": 7.6,
    "height": "20'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 35,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006241",
    "lng": "W-87.658259",
    "dbh": 6.5,
    "height": "15'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 36,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006244",
    "lng": "W-87.658251",
    "dbh": 8.6,
    "height": "20'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "top is sparse"
  },
  {
    "Number": 37,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006124",
    "lng": "W-87.658133",
    "dbh": 17.2,
    "height": "55'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 38,
    "Species": "Crabapple (Malus)",
    "lat": "N42.006170",
    "lng": "W-87.658159",
    "dbh": 4.1,
    "height": "18'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "old tree; root damage from mower"
  },
  {
    "Number": 39,
    "Species": "Crabapple (Malus)",
    "lat": "N42.006220",
    "lng": "W-87.658192",
    "dbh": 5.4,
    "height": "18'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 3,
    "Notes": "old tree; trunk damage"
  },
  {
    "Number": 40,
    "Species": "Crabapple (Malus)",
    "lat": "N42.006229",
    "lng": "W-87.658148",
    "dbh": 5.4,
    "height": "18'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "old tree"
  },
  {
    "Number": 41,
    "Species": "Downy Hawthorn (Crataegus mollis)",
    "lat": "N42.006209",
    "lng": "W-87.658022",
    "dbh": 8.1,
    "height": "20'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 1,
    "Notes": "asphalt dumped by roots; 2-trunked"
  },
  {
    "Number": 42,
    "Species": "Eastern Cottonwood (Populus deltoides)",
    "lat": "N42.006280",
    "lng": "W-87.657910",
    "dbh": 35.3,
    "height": "80'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "3-trunks; root damage from mower"
  },
  {
    "Number": 43,
    "Species": "Eastern Cottonwood (Populus deltoides)",
    "lat": "N42.006157",
    "lng": "W-87.657970",
    "dbh": 27.3,
    "height": "80'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "2-trunks; girdling roots; root damage from mower"
  },
  {
    "Number": 44,
    "Species": "White Mulberry (Morus alba)",
    "lat": "N42.006251",
    "lng": "W-87.657999",
    "dbh": 2.4,
    "height": "35'",
    "Crown Condition": 4,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "2-trunks"
  },
  {
    "Number": 45,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.006252",
    "lng": "W-87.657999",
    "dbh": 24.2,
    "height": "55'",
    "Crown Condition": 1,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "lots of asphalt; leaves wilted"
  },
  {
    "Number": 46,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.005693",
    "lng": "W-87.658466",
    "dbh": 19.7,
    "height": "35'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 47,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005772",
    "lng": "W-87.658317",
    "dbh": 17.5,
    "height": "25'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 48,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.005676",
    "lng": "W-87.657922",
    "dbh": 10.5,
    "height": "10'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 49,
    "Species": "Hawthorn (Crateagus)",
    "lat": "N42.005684",
    "lng": "W-87.658125",
    "dbh": 7.6,
    "height": "15'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 50,
    "Species": "Hawthorn (Crateagus)",
    "lat": "N42.005730",
    "lng": "W-87.658028",
    "dbh": 6.3,
    "height": "15'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 4,
    "Notes": "very shaded"
  },
  {
    "Number": 51,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005724",
    "lng": "W-87.657950",
    "dbh": 23.2,
    "height": "45'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 52,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005776",
    "lng": "W-87.657937",
    "dbh": 23.5,
    "height": "50'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 53,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005762",
    "lng": "W-87.658026",
    "dbh": 18.4,
    "height": "50'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "shaded on north"
  },
  {
    "Number": 54,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005795",
    "lng": "W-87.658025",
    "dbh": 16.5,
    "height": "50'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 55,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.005829",
    "lng": "W-87.658011",
    "dbh": 19.7,
    "height": "50'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 56,
    "Species": "Silver Maple (Acer saccharinum)",
    "lat": "N42.005849",
    "lng": "W-87.658005",
    "dbh": 30.2,
    "height": "60'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 57,
    "Species": "Hawthorn (Crateagus)",
    "lat": "N42.006016",
    "lng": "W-87.658062",
    "dbh": 8.5,
    "height": "15'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 58,
    "Species": "Elm (Siberian, Ulmnus Pumila)",
    "lat": "N42.005984",
    "lng": "W-87.658111",
    "dbh": 2.8,
    "height": "10'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "two leaders with enclosed bark"
  },
  {
    "Number": 59,
    "Species": "Littleleaf Linden (Tilia americana)",
    "lat": "N42.005008",
    "lng": "W-87.658193",
    "dbh": 3.1,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 60,
    "Species": "Littleleaf Linden (Tilia cordata)",
    "lat": "N42.005987",
    "lng": "W-87.658208",
    "dbh": 16.5,
    "height": "40'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 61,
    "Species": "Red Oak (Quercus rubra)",
    "lat": "N42.005849",
    "lng": "W-87.658127",
    "dbh": 2.8,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 62,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006385   +/-16",
    "lng": "W-87.657998",
    "dbh": 14,
    "height": "20'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018). The pruning that was done on the trees in this section was only to branches that were hanging over the sidewalk. Dead branches were not removed."
  },
  {
    "Number": 63,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006416",
    "lng": "W-87.658003",
    "dbh": 2.5,
    "height": "14'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "double trunk; branches pruned away from sidewalk (2018)"
  },
  {
    "Number": 64,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006466",
    "lng": "W-87.6580091",
    "dbh": 6,
    "height": "14'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "3 trunks; roots exposed; branches pruned away from sidewalk (2018)"
  },
  {
    "Number": 65,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006567",
    "lng": "W-87.658025",
    "dbh": 17.5,
    "height": "25'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018); enclosed bark"
  },
  {
    "Number": 66,
    "Species": "White Pine (Pinus strobus)",
    "lat": "N42.006649",
    "lng": "W-87.658102",
    "dbh": 13,
    "height": "25'",
    "Crown Condition": 1,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018); half-dead"
  },
  {
    "Number": 67,
    "Species": "White Pine (Pinus strobus)",
    "lat": "N42.006647",
    "lng": "W-87.658136",
    "dbh": 15.1,
    "height": "25'",
    "Crown Condition": 1,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018); 40% of needles are yellow"
  },
  {
    "Number": 68,
    "Species": "White Pine (Pinus strobus)",
    "lat": "N42.006676",
    "lng": "W-87.658227",
    "dbh": 11.94,
    "height": "25'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018); yellow needles; minor dead branch"
  },
  {
    "Number": 69,
    "Species": "White Pine (Pinus strobus)",
    "lat": "N42.006676",
    "lng": "W-87.658422",
    "dbh": 13.5,
    "height": "25'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": "girdling roots; branches pruned away from sidewalk (2018); yellow needles; minor dead branch"
  },
  {
    "Number": 70,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006656",
    "lng": "W-87.658478",
    "dbh": 11.1,
    "height": "15'",
    "Crown Condition": 1,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "girdling roots; lots of fungus; 25% dead branches"
  },
  {
    "Number": 71,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.006622",
    "lng": "W-87.658593",
    "dbh": 2.8,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "planted in 2016"
  },
  {
    "Number": 72,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.006668",
    "lng": "W-87.658673",
    "dbh": 3.1,
    "height": "15'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "planted in 2016"
  },
  {
    "Number": 73,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.006657",
    "lng": "W-87.658737",
    "dbh": 3.1,
    "height": "12'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "planted in 2016"
  },
  {
    "Number": 74,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006542",
    "lng": "W-87.659817",
    "dbh": 15.2,
    "height": "15'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "multiple trunks; exposed roots; enclosed bark"
  },
  {
    "Number": 75,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006505",
    "lng": "W-87.658919",
    "dbh": 11.4,
    "height": "14'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "two trunks; enclosed bark"
  },
  {
    "Number": 76,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006338",
    "lng": "W-87.658885",
    "dbh": 23.2,
    "height": "35'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 77,
    "Species": "Weeping willow (Salix babylonica)",
    "lat": "N42.006036",
    "lng": "W-87.657615 (+/-16 ft)",
    "dbh": 23.5,
    "height": "28'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "growing in sand; suckers at base of tree"
  },
  {
    "Number": 78,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006408",
    "lng": "W-87.657882",
    "dbh": 3,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "wire cage was left on when tree was planting (may be from 2016 planting, or earlier)"
  },
  {
    "Number": 79,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006408",
    "lng": "W-87.657824",
    "dbh": 4.4,
    "height": "11'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "four trunks"
  },
  {
    "Number": 80,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006478  +/-16",
    "lng": "W-87.657869",
    "dbh": 14.6,
    "height": "24'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "girdled roots"
  },
  {
    "Number": 81,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006507",
    "lng": "W-87.657883",
    "dbh": 15.5,
    "height": "24'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 82,
    "Species": "Thornless Hawthorn (Crataegus)",
    "lat": "N42.006537",
    "lng": "W-87.657843",
    "dbh": 4.7,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 83,
    "Species": "Thornless Hawthorn (Crataegus)",
    "lat": "N42.006671",
    "lng": "W-87.657795",
    "dbh": 3.1,
    "height": "11'",
    "Crown Condition": 3,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "bark has rotted away at base of trunk"
  },
  {
    "Number": 84,
    "Species": "Thornless Hawthorn (Crataegus)",
    "lat": "N42.006584",
    "lng": "W-87.657829",
    "dbh": 6,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 85,
    "Species": "Kentucky Coffee Tree (Gymnocladus dioicus)",
    "lat": "N42.006543",
    "lng": "W-87.657656",
    "dbh": 2.2,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 86,
    "Species": "Kentucky Coffee Tree (Gymnocladus dioicus)",
    "lat": "N42.006623",
    "lng": "W-87.657904",
    "dbh": 2.2,
    "height": "11'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 87,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006631",
    "lng": "W-87.657941",
    "dbh": 16.5,
    "height": "32'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "a little bit of witches broom"
  },
  {
    "Number": 88,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006797",
    "lng": "W-87.657916",
    "dbh": 17.5,
    "height": "30'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "could use pruning"
  },
  {
    "Number": 89,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006743",
    "lng": "W-87.657861",
    "dbh": 4,
    "height": "12'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "2-trunked"
  },
  {
    "Number": 90,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006767",
    "lng": "W-87.657879",
    "dbh": 4.6,
    "height": "11'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "4-trunked"
  },
  {
    "Number": 91,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.006755",
    "lng": "W-87.657957",
    "dbh": 4.7,
    "height": "12'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "3-trunked"
  },
  {
    "Number": 92,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.006680",
    "lng": "W-87.657013",
    "dbh": 15.9,
    "height": "33'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "girdled roots"
  },
  {
    "Number": 93,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.006680",
    "lng": "W-87.657067",
    "dbh": 12.4,
    "height": "33'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "girdled roots; branches pruned away from sidewalk to make room for trucks (2018)"
  },
  {
    "Number": 94,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.006809",
    "lng": "W-87.657911",
    "dbh": 2.7,
    "height": "12'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "When tree was planted in 2016, thick bands were left on the tree about 10' up. They should get removed so they don't strangle the leader."
  },
  {
    "Number": 95,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006974",
    "lng": "W-87.657709",
    "dbh": 22.1,
    "height": "28'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "Bark missing at base"
  },
  {
    "Number": 96,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.006956",
    "lng": "W-87.657066",
    "dbh": 3,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "Had tag IDing it as Ulmus 'Princeton' still on it from when it was planted (2016). There are quite of lot of other similar elms that were planted at the same time, so I'm inferring that they are also Princeton. These trees have a very vertical branching pattern that is prone to developing enclosed bark."
  },
  {
    "Number": 97,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.006975",
    "lng": "W-87.657052",
    "dbh": 26.7,
    "height": "35'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 98,
    "Species": "Kentucky Coffee Tree (Gymnocladus dioicus)",
    "lat": "N42.007005",
    "lng": "W-87.657924",
    "dbh": 2.5,
    "height": "10'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 99,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007069",
    "lng": "W-87.657886",
    "dbh": 2.8,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 100,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.007144",
    "lng": "W-87.657968",
    "dbh": 11.4,
    "height": "22'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 101,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.006109",
    "lng": "W-87.658006",
    "dbh": 21.1,
    "height": "30'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "Dark vertical streaks—this tree has been burned—probably by coals"
  },
  {
    "Number": 102,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "W42.007140",
    "lng": "W-87.658099",
    "dbh": 8.9,
    "height": "25'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 3,
    "Notes": "Trunk is hollow with a big gaping hole at the base"
  },
  {
    "Number": 103,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006612",
    "lng": "W-87.658144",
    "dbh": 15.9,
    "height": "36'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 104,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006630",
    "lng": "W-87.658140",
    "dbh": 9.5,
    "height": "23'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "branches with no needles or yellow needles. Lots of woodpecker holes."
  },
  {
    "Number": 105,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006760",
    "lng": "W-87.658200",
    "dbh": 10.8,
    "height": "26'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "some die-back of needles"
  },
  {
    "Number": 106,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006800",
    "lng": "W-87.658160",
    "dbh": 7.8,
    "height": "21'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "some die-back of needles"
  },
  {
    "Number": 107,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006660",
    "lng": "W-87.658060",
    "dbh": 15.2,
    "height": "36'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "some branches pruned away from sidewalk to make room for trucks (2018)"
  },
  {
    "Number": 108,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.006740",
    "lng": "W-87.658180",
    "dbh": 15.4,
    "height": "35'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 109,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006990",
    "lng": "W-87.658440",
    "dbh": 13.5,
    "height": "29'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 110,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006882",
    "lng": "W-87.658361",
    "dbh": 10.9,
    "height": "19'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 111,
    "Species": "Scots Pine (Pinus sylvestris)",
    "lat": "N42.006899",
    "lng": "W-87.658420",
    "dbh": 13,
    "height": "19'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 112,
    "Species": "Bur oak (Quercus macrocarpa)",
    "lat": "N42.006930",
    "lng": "W-87.658430",
    "dbh": 4.2,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 113,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.006950",
    "lng": "W-87.658557",
    "dbh": 13.3,
    "height": "31'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "girdling roots"
  },
  {
    "Number": 114,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.007000",
    "lng": "W-87.658520",
    "dbh": 15.5,
    "height": "31'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "girdling roots"
  },
  {
    "Number": 115,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.007007",
    "lng": "W-87.658646",
    "dbh": 15.4,
    "height": "36'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "rope stuck between branches"
  },
  {
    "Number": 116,
    "Species": "Hawthorn (Crateagus)",
    "lat": "N42.007153",
    "lng": "W-87.658599",
    "dbh": 7.7,
    "height": "30'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 4,
    "Notes": "multi-trunked (7); stressed regrowth; trunks and branches rubbing"
  },
  {
    "Number": 117,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.007159",
    "lng": "W-87.658847",
    "dbh": 20.3,
    "height": "46'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 118,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.007210",
    "lng": "W-87.658760",
    "dbh": 43.6,
    "height": "48'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Biggest DBH in Loyola Park. Healthy looking!"
  },
  {
    "Number": 119,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.007275",
    "lng": "W-87.658812",
    "dbh": 23.2,
    "height": "43'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 120,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.007424",
    "lng": "W-87.658977",
    "dbh": 3,
    "height": "12'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "planted in 2016."
  },
  {
    "Number": 121,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007457",
    "lng": "W-87.658999",
    "dbh": 2,
    "height": "15'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "When tree was planted in 2016, thick bands were left on the tree about 10' up. The bands should get removed. planted in 2016"
  },
  {
    "Number": 122,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007453",
    "lng": "W-87.659007",
    "dbh": 3,
    "height": "15'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 123,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007458",
    "lng": "W-87.659020",
    "dbh": 3,
    "height": "13'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "When tree was planted in 2016, thick bands were left on the tree about 10' up. The bands should get removed. planted in 2016"
  },
  {
    "Number": 124,
    "Species": "Red Oak (Quercus rubra)",
    "lat": "N42.007630",
    "lng": "W-87.659000",
    "dbh": 5.2,
    "height": "22'",
    "Crown Condition": 2,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "some dead branches; planted in 2016?"
  },
  {
    "Number": 125,
    "Species": "Red Oak (Quercus rubra)",
    "lat": "N42.007680",
    "lng": "W-87.658987",
    "dbh": 5.8,
    "height": "26'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "some dead branches; planted in 2016?"
  },
  {
    "Number": 126,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007810",
    "lng": "W-87.659010",
    "dbh": 2.7,
    "height": "48'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 4,
    "Notes": "multiple competing branches; dead branches; July 2018: lots of leaf die-off; planted in 2016"
  },
  {
    "Number": 127,
    "Species": "Honey Locust (Gleditsia triacanthos inermis) (thornless)",
    "lat": "N42.007880",
    "lng": "W-87.658920",
    "dbh": 2.7,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "could use bottom branch pruned off; planted in 2016"
  },
  {
    "Number": 128,
    "Species": "Kentucky Coffee Tree (Gymnocladus dioicus)",
    "lat": "N42.007800",
    "lng": "W-87.658940",
    "dbh": 2.5,
    "height": "10'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 129,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007800",
    "lng": "W-87.658970",
    "dbh": 3.1,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 130,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.007660",
    "lng": "W-87.658880",
    "dbh": 2.8,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 131,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.007780",
    "lng": "W-87.658680",
    "dbh": 19.4,
    "height": "36'",
    "Crown Condition": 1,
    "Trunk Condition": 1,
    "Root Condition": 2,
    "Notes": "DYING"
  },
  {
    "Number": 132,
    "Species": "Sugar Maple (Acer saccharum)",
    "lat": "N42.007730",
    "lng": "W-87.658730",
    "dbh": 19.4,
    "height": "40'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 133,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.007790",
    "lng": "W-87.658530",
    "dbh": 2.5,
    "height": "10'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "sandy soil; multi-trunked; needs pruning"
  },
  {
    "Number": 134,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.007702",
    "lng": "W-87.658453",
    "dbh": 3.1,
    "height": "9'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "sandy soil; multi-trunked; needs pruning"
  },
  {
    "Number": 135,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.007696",
    "lng": "W-87.658413",
    "dbh": 3.8,
    "height": "9'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "growing over sidewalk; needs pruning"
  },
  {
    "Number": 136,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007508  +/-16 ft",
    "lng": "W-87.657391",
    "dbh": 3.1,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "tape or thick bands @ top of tree from when it was planted in 2016. Bands should get removed."
  },
  {
    "Number": 137,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.007604",
    "lng": "W-87.658355",
    "dbh": 1.9,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "scratched-up trunk; girdling roots; nail in bark"
  },
  {
    "Number": 138,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007527",
    "lng": "W-87.658221",
    "dbh": 3,
    "height": "15'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 2,
    "Notes": "roots have been severed by lawn mower"
  },
  {
    "Number": 139,
    "Species": "Red Maple (Acer rubrum)",
    "lat": "N42.007580",
    "lng": "W-87.658344",
    "dbh": 20.7,
    "height": "30'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "some missing bark (sealed-over); hot coal damage"
  },
  {
    "Number": 140,
    "Species": "Red Maple (Acer rubrum)",
    "lat": "N42.007438",
    "lng": "W-87.658213",
    "dbh": 20.7,
    "height": "31'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "hot coal damage"
  },
  {
    "Number": 141,
    "Species": "Red Maple (Acer rubrum)",
    "lat": "N42.007443",
    "lng": "W-87.658190",
    "dbh": 21.8,
    "height": "20'",
    "Crown Condition": 2,
    "Trunk Condition": 2,
    "Root Condition": 2,
    "Notes": "hot coal damage"
  },
  {
    "Number": 142,
    "Species": "Honey Locust (Gleditsia triacanthos)",
    "lat": "N42.007551",
    "lng": "W-87.658107",
    "dbh": 2.5,
    "height": "14'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "planted in 2016"
  },
  {
    "Number": 143,
    "Species": "Catalpa (Catalpa speciosa)",
    "lat": "N42.007488",
    "lng": "W-87.658006",
    "dbh": 2.5,
    "height": "9'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "planted in 2016. Some damage on bark. Some broken branches (wind damage?)"
  },
  {
    "Number": 144,
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007470",
    "lng": "W-87.657997",
    "dbh": 1.8,
    "height": "12'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 4,
    "Notes": "planted in 2016. Damage to bark (knife?) Sap bleeding from gashes."
  },
  {
    "Number": 145,
    "Species": "Cornelia Cherry Dogwood (Cornus mas)",
    "lat": "N42.007416",
    "lng": "W-87.657900",
    "dbh": 2,
    "height": "9'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": "Multi-stemmed shrub. Lots of crossing branches. Could use pruning."
  },
  {
    "Number": 146,
    "Species": "Maple (Sugar? Red?)",
    "lat": "N42.007350",
    "lng": "W-87.658011",
    "dbh": 10.7,
    "height": "29'",
    "Crown Condition": 4,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": "Carving on trunk (romantic); girdling roots; missing/sealed-over bark. White at base of trunk (coal damage?)"
  },
  {
    "Number": 147,
    "Species": "Basswood (Tilia americana)",
    "lat": "N42.007357",
    "lng": "W-87.657976",
    "dbh": 8.3,
    "height": "25'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "Trunk: enclosed bark. Some white at base of tree charcoal damage?)  Missing, sealed-over bark."
  },
  {
    "Number": 148,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007307",
    "lng": "W-87.657898",
    "dbh": 2.7,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "When tree was planted in 2016, thick bands were left on the tree"
  },
  {
    "Number": 149,
    "Species": "Tree stump-unknown",
    "lat": "N42.007238",
    "lng": "W-87.657932",
    "dbh": 6.3,
    "height": "3'",
    "Crown Condition": 1,
    "Trunk Condition": 1,
    "Root Condition": 1,
    "Notes": "long-gone tree. Just stump left. Isn't really doing anyone any harm."
  },
  {
    "Number": 150,
    "Species": "Chinkapin Oak (Quercus muehlenbergii)",
    "lat": "N42.007235",
    "lng": "W-87.657989",
    "dbh": 5.7,
    "height": "18'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Broken branches. Could use pruning."
  },
  {
    "Number": 151,
    "Species": "White Ash (Fraxinus americana) ?",
    "lat": "N42.007796",
    "lng": "W-87.65619",
    "dbh": 8,
    "height": "18'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": "In island at end of street (may not be a park district tree?). Stands in water after heavy rains. Innoculated in 2013."
  },
  {
    "Number": 152,
    "Species": "White Pine (Pinus strobus)",
    "lat": "N42.006790",
    "lng": "W-87.658507",
    "dbh": 14,
    "height": "30'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 3,
    "Notes": "some branches pruned away from sidewalk to make room for trucks (2018)"
  },
  {
    "Number": 153,
    "Species": "Ash (Fraxinus)",
    "lat": "N42.006800",
    "lng": "W-87.658908",
    "dbh": 13,
    "height": "36'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "multi-trunked (3); some recently (2018) cut. Stands in water after heavy rains."
  },
  {
    "Number": 154,
    "Species": "Honey locust (Gladitsia triacanthos)",
    "lat": "N42.006800",
    "lng": "W-87.659082",
    "dbh": 29.6,
    "height": "50'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": "Split trunk. Leaning: growing away from larger tree to the north."
  },
  {
    "Number": 155,
    "Species": "Hackberry (Celtis occidentalis)",
    "lat": "N42.006884",
    "lng": "W-87.659092",
    "dbh": 12,
    "height": "25'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 156,
    "Species": "Norway Maple (Acer platanoides)",
    "lat": "N42.006942",
    "lng": "W-87.659085",
    "dbh": 13.5,
    "height": "30'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 3,
    "Notes": ""
  },
  {
    "Number": 157,
    "Species": "Crabapple (Malus species)",
    "lat": "N42.007021",
    "lng": "W-87.659129",
    "dbh": 3.3,
    "height": "10'",
    "Crown Condition": 4,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 158,
    "Species": "Kentucky Coffee Tree (Gymnocladus dioicus)",
    "lat": "N42.006988",
    "lng": "W-87.658975",
    "dbh": 2.1,
    "height": "11'",
    "Crown Condition": 3,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Some broken branches. Dark sap oozing from trunk."
  },
  {
    "Number": 159,
    "Species": "Red Oak (Quercus rubra)",
    "lat": "N42.006941",
    "lng": "W-87.658966",
    "dbh": 29.6,
    "height": "45'",
    "Crown Condition": 3,
    "Trunk Condition": 2,
    "Root Condition": 4,
    "Notes": "Broken branches"
  },
  {
    "Number": 160,
    "Species": "Honey locust (Gladitsia triacanthos)",
    "lat": "N42.007100",
    "lng": "W-87.659148",
    "dbh": 29,
    "height": "50'",
    "Crown Condition": 3,
    "Trunk Condition": 3,
    "Root Condition": 4,
    "Notes": ""
  },
  {
    "Number": 161,
    "Species": "Maple (Acer x \"Freemanii ?)",
    "lat": "N42.007319",
    "lng": "W-87.659113",
    "dbh": 3.2,
    "height": "13'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Planted in 2016."
  },
  {
    "Number": "161B",
    "Species": "Elm (Ulmus 'Princeton')",
    "lat": "N42.007234",
    "lng": "W-87.659143",
    "dbh": 10,
    "height": "16'",
    "Crown Condition": 4,
    "Trunk Condition": 4,
    "Root Condition": 4,
    "Notes": "Planted in 2016. When tree was planted, thick bands were left on the tree."
  },
  {
    "Number": 162,
    "Species": "Honey locust (Gladitsia triacanthos)",
    "lat": "N42.007339",
    "lng": "W-87.659088",
    "dbh": 27.7,
    "height": "45'",
    "Crown Condition": 2,
    "Trunk Condition": 3,
    "Root Condition": 2,
    "Notes": ""
  },
  {
    "Number": 163,
    "Species": "Honey locust (Gladitsia triacanthos)",
    "lat": "N42.007374",
    "lng": "W-87.659210",
    "dbh": 29.6,
    "height": "42'",
    "Crown Condition": 2,
    "Trunk Condition": 1,
    "Root Condition": 3,
    "Notes": "Leaning. Epicormic shoots. Peeling bark. Many dead branches.  "
  }
];

